### YamlMime:PowershellCmdlet
summary: |-
  Display detailed information about PowerShell errors, with extended details for Azure PowerShell errors.
module: Az.Accounts
notes: ""
inputs:
- name: <xref href="System.Management.Automation.ErrorRecord" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Azure.Commands.Profile.Errors.AzureErrorRecord" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Profile.Errors.AzureExceptionRecord" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Azure.Commands.Profile.Errors.AzureRestExceptionRecord" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Resolve-AzError [[-Error] <ErrorRecord[]>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
- Resolve-AzError [-Last] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>]
examples:
- title: 'Example 1: Resolve the Last Error'
  code: |-
    PS C:\> Resolve-AzError -Last

       HistoryId: 3


    Message        : Run Connect-AzAccount to login.
    StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext() in AzureRmCmdlet.cs:line 85
                        at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.LogCmdletStartInvocationInfo() in AzureRmCmdlet.cs:line 269
                        at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() inAzurePSCmdlet.cs:line 299
                        at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.BeginProcessing() in AzureRmCmdlet.cs:line 320
                        at Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand.BeginProcessing() in GetAzureRMSubscription.cs:line 49
                        at System.Management.Automation.Cmdlet.DoBeginProcessing()
                        at System.Management.Automation.CommandProcessorBase.DoBegin()
    Exception      : System.Management.Automation.PSInvalidOperationException
    InvocationInfo : {Get-AzSubscription}
    Line           : Get-AzSubscription
    Position       : At line:1 char:1
                     + Get-AzSubscription
                     + ~~~~~~~~~~~~~~~~~~~~~~~
    HistoryId      : 3
  description: |-
    Get details of the last error.
  summary: ""
- title: 'Example 2: Resolve all Errors in the Session'
  code: |-
    PS C:\> Resolve-AzError


       HistoryId: 8


    RequestId      : b61309e8-09c9-4f0d-ba56-08a6b28c731d
    Message        : Resource group 'contoso' could not be found.
    ServerMessage  : ResourceGroupNotFound: Resource group 'contoso' could not be found.
                     (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
    ServerResponse : {NotFound}
    RequestMessage : {GET https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/co
                     ntoso/providers/Microsoft.Storage/storageAccounts/contoso?api-version=2016-12-01}
    InvocationInfo : {Get-AzStorageAccount}
    Line           : Get-AzStorageAccount -ResourceGroupName contoso -Name contoso
    Position       : At line:1 char:1
                     + Get-AzStorageAccount -ResourceGroupName contoso -Name contoso
                     + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    StackTrace     :    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync
                     >d__8.MoveNext()
                     --- End of stack trace from previous location where exception was thrown ---
                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                        at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<GetPropertiesAsync>d__7.
                     MoveNext()
                     --- End of stack trace from previous location where exception was thrown ---
                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                        at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.GetProperties(IStorageAcc
                     ountsOperations operations, String resourceGroupName, String accountName)
                        at Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet() in C:\
                     zd\azure-powershell\src\ResourceManager\Storage\Commands.Management.Storage\StorageAccount\GetAzureSto
                     rageAccount.cs:line 70
                        at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in
                     C:\zd\azure-powershell\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642
    HistoryId      : 8


       HistoryId: 5


    Message        : Run Connect-AzAccount to login.
    StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext() in C:\zd\azur
                     e-powershell\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRmCmdlet.cs:line 85
                        at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.LogCmdletStartInvocationInfo() in
                     C:\zd\azure-powershell\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRmCmdlet.cs:lin
                     e 269
                        at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() in
                     C:\zd\azure-powershell\src\Common\Commands.Common\AzurePSCmdlet.cs:line 299
                        at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.BeginProcessing() in C:\zd\azure-p
                     owershell\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRmCmdlet.cs:line 320
                        at Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand.BeginProcessing() in C:\zd\azure-
                     powershell\src\ResourceManager\Profile\Commands.Profile\Subscription\GetAzureRMSubscription.cs:line 49
                        at System.Management.Automation.Cmdlet.DoBeginProcessing()
                        at System.Management.Automation.CommandProcessorBase.DoBegin()
    Exception      : System.Management.Automation.PSInvalidOperationException
    InvocationInfo : {Get-AzSubscription}
    Line           : Get-AzSubscription
    Position       : At line:1 char:1
                     + Get-AzSubscription
                     + ~~~~~~~~~~~~~~~~~~~~~~~
    HistoryId      : 5
  description: |-
    Get details of all errors that have occurred in the current session.
  summary: ""
- title: 'Example 3: Resolve a Specific Error'
  code: |-
    PS C:\> Resolve-AzError $Error[0]


       HistoryId: 8


    RequestId      : b61309e8-09c9-4f0d-ba56-08a6b28c731d
    Message        : Resource group 'contoso' could not be found.
    ServerMessage  : ResourceGroupNotFound: Resource group 'contoso' could not be found.
                     (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
    ServerResponse : {NotFound}
    RequestMessage : {GET https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/co
                     ntoso/providers/Microsoft.Storage/storageAccounts/contoso?api-version=2016-12-01}
    InvocationInfo : {Get-AzStorageAccount}
    Line           : Get-AzStorageAccount -ResourceGroupName contoso -Name contoso
    Position       : At line:1 char:1
                     + Get-AzStorageAccount -ResourceGroupName contoso -Name contoso
                     + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    StackTrace     :    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync
                     >d__8.MoveNext()
                     --- End of stack trace from previous location where exception was thrown ---
                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                        at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<GetPropertiesAsync>d__7.
                     MoveNext()
                     --- End of stack trace from previous location where exception was thrown ---
                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                        at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.GetProperties(IStorageAcc
                     ountsOperations operations, String resourceGroupName, String accountName)
                        at Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet() in C:\
                     zd\azure-powershell\src\ResourceManager\Storage\Commands.Management.Storage\StorageAccount\GetAzureSto
                     rageAccount.cs:line 70
                        at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in
                     C:\zd\azure-powershell\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642
    HistoryId      : 8
  description: |-
    Get details of the specified error.
  summary: ""
parameters:
- type: <xref href="Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer" data-throw-if-not-resolved="False" />
  name: DefaultProfile
  description: |+
    The credentials, tenant and subscription used for communication with azure

  defaultValue: None
  position: Named
  aliases: AzContext, AzureRmContext, AzureCredential
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.ErrorRecord" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Error
  description: |+
    One or more error records to resolve.  If no parameters are specified, all errors in the session are resolved.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Last
  isRequired: true
  description: |+
    Resolve only the last error that occurred in the session.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Az.Accounts.Resolve-AzError
name: Resolve-AzError
description: |-
  Resolves and displays detailed information about errors in the current PowerShell session, including where the error 
  occurred in script, stack trace, and all inner and aggregate exceptions. For Azure PowerShell errors provides 
  additional detail in debugging service issues, including complete detail about the request and server response 
  that caused the error.
metadata:
  external help file: Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll-Help.xml
  Module Name: Az.Accounts
  online version: https://docs.microsoft.com/en-us/powershell/module/az.accounts/resolve-azerror
  schema: 2.0.0
  content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Accounts/Accounts/help/Resolve-AzError.md
  original_content_git_url: https://github.com/Azure/azure-powershell/blob/master/src/Accounts/Accounts/help/Resolve-AzError.md
